trigger: none

pool:
 vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Debug'

steps:

- task: InlinePowershell@1
  inputs:
    Script: '
$url = "https://storageaccountrolleae6c.blob.core.windows.net/roller-coaster/TemplateFill.trx"
$output = $(System.DefaultWorkingDirectory) + "\TemplateFill.trx"
$start_time = Get-Date

$wc = New-Object System.Net.WebClient
$wc.DownloadFile($url, $output)'
